# Generated by Django 5.0.6 on 2024-07-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customer_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mob',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('SU', 'Shoes'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('FP', 'Fitness Product'), ('7T', '7T7T')], max_length=2),
        ),
    ]
